-- MySQL Script generated by MySQL Workbench
-- Tue Oct 27 15:52:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Etudiant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Etudiant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `diplome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NOT NULL,
  `Etudiant_id` INT NOT NULL,
  PRIMARY KEY (`idAdresse`),
  UNIQUE INDEX `idAdresse_UNIQUE` (`idAdresse` ASC) ,
  INDEX `fk_Adresse_Etudiant1_idx` (`Etudiant_id` ASC) ,
  CONSTRAINT `fk_Adresse_Etudiant1`
    FOREIGN KEY (`Etudiant_id`)
    REFERENCES `mydb`.`Etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Professeur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Professeur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `competence` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Salle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Salle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cours` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `heureDebut` DATETIME NULL,
  `heureFin` DATETIME NULL,
  `Professeur_id` INT NOT NULL,
  `Salle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cours_Professeur1_idx` (`Professeur_id` ASC) ,
  INDEX `fk_Cours_Salle1_idx` (`Salle_id` ASC) ,
  CONSTRAINT `fk_Cours_Professeur1`
    FOREIGN KEY (`Professeur_id`)
    REFERENCES `mydb`.`Professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cours_Salle1`
    FOREIGN KEY (`Salle_id`)
    REFERENCES `mydb`.`Salle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NOT NULL,
  `Etudiant_id` INT NOT NULL,
  `Cours_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Participant_Etudiant1_idx` (`Etudiant_id` ASC) ,
  INDEX `fk_Participant_Cours1_idx` (`Cours_id` ASC) ,
  CONSTRAINT `fk_Participant_Etudiant1`
    FOREIGN KEY (`Etudiant_id`)
    REFERENCES `mydb`.`Etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participant_Cours1`
    FOREIGN KEY (`Cours_id`)
    REFERENCES `mydb`.`Cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
